### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by okatticus** [okatticus/Sunshine#4]
Log:
06-23 13:06:05.493 32084-32084/com.example.android.sunshine E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
06-23 13:06:05.673 32084-32121/com.example.android.sunshine E/SQLiteLog: (1) no such column: dateASC
06-23 13:06:05.673 32084-32121/com.example.android.sunshine E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
                                                                              Process: com.example.android.sunshine, PID: 32084
                                                                              java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:841)
                                                                               Caused by: android.database.sqlite.SQLiteException: no such column: dateASC (code 1): , while compiling: SELECT weather._id, date, short_desc, max, min, loc_setting FROM weather INNER JOIN location ON weather.location_id=location._id WHERE (location.loc_setting =? AND date >= ? ) ORDER BY dateASC
                                                                                  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                                  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                                  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                  at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                  at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
                                                                                  at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
                                                                                  at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
                                                                                  at com.example.android.sunshine.data.WeatherProvider.getWeatherByLocationSetting(WeatherProvider.java:75)
                                                                                  at com.example.android.sunshine.data.WeatherProvider.query(WeatherProvider.java:114)
                                                                                  at android.content.ContentProvider.query(ContentProvider.java:857)
                                                                                  at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
                                                                                  at android.content.ContentResolver.query(ContentResolver.java:461)
                                                                                  at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:33)
                                                                                  at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
                                                                                  at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
                                                                                  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
                                                                                  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
                                                                                  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
                                                                                  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                                                                                  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
                                                                                  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                  at java.lang.Thread.run(Thread.java:841) 
06-23 13:06:06.033 32084-32122/com.example.android.sunshine E/FetchWeatherTask: Index 14 out of range [0..14)
                                                                                org.json.JSONException: Index 14 out of range [0..14)
                                                                                    at org.json.JSONArray.get(JSONArray.java:282)
                                                                                    at org.json.JSONArray.getJSONObject(JSONArray.java:510)
                                                                                    at com.example.android.sunshine.data.FetchWeatherTask.doInBackground(FetchWeatherTask.java:150)
                                                                                    at com.example.android.sunshine.data.FetchWeatherTask.doInBackground(FetchWeatherTask.java:32)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by octacode** [comment]
Hi! @okatticus You could have done it this way

**Logcat for the crash**

`06-23 13:06:05.493 32084-32084/com.example.android.sunshine E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
06-23 13:06:05.673 32084-32121/com.example.android.sunshine E/SQLiteLog: (1) no such column: dateASC
06-23 13:06:05.673 32084-32121/com.example.android.sunshine E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
Process: com.example.android.sunshine, PID: 32084
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: android.database.sqlite.SQLiteException: no such column: dateASC (code 1): , while compiling: SELECT weather._id, date, short_desc, max, min, loc_setting FROM weather INNER JOIN location ON weather.location_id=location._id WHERE (location.loc_setting =? AND date >= ? ) ORDER BY dateASC
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
at com.example.android.sunshine.data.WeatherProvider.getWeatherByLocationSetting(WeatherProvider.java:75)
at com.example.android.sunshine.data.WeatherProvider.query(WeatherProvider.java:114)
at android.content.ContentProvider.query(ContentProvider.java:857)
at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
at android.content.ContentResolver.query(ContentResolver.java:461)
at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:33)
at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 
06-23 13:06:06.033 32084-32122/com.example.android.sunshine E/FetchWeatherTask: Index 14 out of range [0..14)
org.json.JSONException: Index 14 out of range [0..14)
at org.json.JSONArray.get(JSONArray.java:282)
at org.json.JSONArray.getJSONObject(JSONArray.java:510)
at com.example.android.sunshine.data.FetchWeatherTask.doInBackground(FetchWeatherTask.java:150)
at com.example.android.sunshine.data.FetchWeatherTask.doInBackground(FetchWeatherTask.java:32)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)`

***And one more thing you could have mentioned how to replicate the crash***

Cheers!

**Comment by okatticus** [comment]
Thanks for the tip!
